name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag oocd-builder
    - run: mkdir out
    - run: docker run --volume=out:/out --entrypoint=/bin/build-oocd.sh oocd-builder
